//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Integradora.ECommerce.Infracommerce.WebServiceClientes {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CustomerServicesBinding", Namespace="http://www.accurate.com/acec/CustomerServices")]
    public partial class CustomerServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback notifyCustomerCreationOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateCustomerOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CustomerServices() {
            this.Url = global::Integradora.Biblioteca.Dictionaries.Settings.InfracommerceURL_Customer();
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event notifyCustomerCreationCompletedEventHandler notifyCustomerCreationCompleted;
        
        /// <remarks/>
        public event updateCustomerCompletedEventHandler updateCustomerCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("notifyCustomerCreation", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("notifyCustomerCreationResponse", Namespace="http://www.accurate.com/acec/CustomerServices")]
        public notifyCustomerCreationResponse notifyCustomerCreation([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.accurate.com/acec/CustomerServices")] notifyCustomerCreationRequest notifyCustomerCreationRequest) {
            object[] results = this.Invoke("notifyCustomerCreation", new object[] {
                        notifyCustomerCreationRequest});
            return ((notifyCustomerCreationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void notifyCustomerCreationAsync(notifyCustomerCreationRequest notifyCustomerCreationRequest) {
            this.notifyCustomerCreationAsync(notifyCustomerCreationRequest, null);
        }
        
        /// <remarks/>
        public void notifyCustomerCreationAsync(notifyCustomerCreationRequest notifyCustomerCreationRequest, object userState) {
            if ((this.notifyCustomerCreationOperationCompleted == null)) {
                this.notifyCustomerCreationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnnotifyCustomerCreationOperationCompleted);
            }
            this.InvokeAsync("notifyCustomerCreation", new object[] {
                        notifyCustomerCreationRequest}, this.notifyCustomerCreationOperationCompleted, userState);
        }
        
        private void OnnotifyCustomerCreationOperationCompleted(object arg) {
            if ((this.notifyCustomerCreationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.notifyCustomerCreationCompleted(this, new notifyCustomerCreationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("updateCustomer", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("updateCustomerResponse", Namespace="http://www.accurate.com/acec/CustomerServices")]
        public updateCustomerResponse updateCustomer([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.accurate.com/acec/CustomerServices")] updateCustomerRequest updateCustomerRequest) {
            object[] results = this.Invoke("updateCustomer", new object[] {
                        updateCustomerRequest});
            return ((updateCustomerResponse)(results[0]));
        }
        
        /// <remarks/>
        public void updateCustomerAsync(updateCustomerRequest updateCustomerRequest) {
            this.updateCustomerAsync(updateCustomerRequest, null);
        }
        
        /// <remarks/>
        public void updateCustomerAsync(updateCustomerRequest updateCustomerRequest, object userState) {
            if ((this.updateCustomerOperationCompleted == null)) {
                this.updateCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateCustomerOperationCompleted);
            }
            this.InvokeAsync("updateCustomer", new object[] {
                        updateCustomerRequest}, this.updateCustomerOperationCompleted, userState);
        }
        
        private void OnupdateCustomerOperationCompleted(object arg) {
            if ((this.updateCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCustomerCompleted(this, new updateCustomerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/CustomerServices")]
    public partial class notifyCustomerCreationRequest {
        
        private customer customerField;
        
        private string storeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.accurate.com/acec/Customer")]
        public customer customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string storeId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accurate.com/acec/Customer")]
    public partial class customer {
        
        private long customerIdField;
        
        private customerCustomerType customerTypeField;
        
        private string titleField;
        
        private string nameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private long documentNrField;
        
        private bool documentNrFieldSpecified;
        
        private long mainAddressIdField;
        
        private bool mainAddressIdFieldSpecified;
        
        private System.DateTime createDateField;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        private customerGender genderField;
        
        private bool genderFieldSpecified;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string stateSubscriptionField;
        
        private int statusField;
        
        private bool statusFieldSpecified;
        
        private string representativeNmField;
        
        private long customerGroupIdField;
        
        private customerOptIn optInField;
        
        private bool optInFieldSpecified;
        
        private customerPartnerOptIn partnerOptInField;
        
        private bool partnerOptInFieldSpecified;
        
        private customerSmsOptIn smsOptInField;
        
        private bool smsOptInFieldSpecified;
        
        private customerSmsTrkOptIn smsTrkOptInField;
        
        private bool smsTrkOptInFieldSpecified;
        
        private orderSummaryInfo orderSummaryInfoField;
        
        private phoneType[] phoneListField;
        
        private addressType[] addressListField;
        
        private customerLoyalty[] customerLoyaltyField;
        
        private string lastVisitedStoreField;
        
        private string newsletterOptoutField;
        
        private string partnerNewsletterOptoutField;
        
        private emailType[] extraEmailListField;
        
        /// <remarks/>
        public long customerId {
            get {
                return this.customerIdField;
            }
            set {
                this.customerIdField = value;
            }
        }
        
        /// <remarks/>
        public customerCustomerType customerType {
            get {
                return this.customerTypeField;
            }
            set {
                this.customerTypeField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public long documentNr {
            get {
                return this.documentNrField;
            }
            set {
                this.documentNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool documentNrSpecified {
            get {
                return this.documentNrFieldSpecified;
            }
            set {
                this.documentNrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long mainAddressId {
            get {
                return this.mainAddressIdField;
            }
            set {
                this.mainAddressIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mainAddressIdSpecified {
            get {
                return this.mainAddressIdFieldSpecified;
            }
            set {
                this.mainAddressIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public customerGender gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool genderSpecified {
            get {
                return this.genderFieldSpecified;
            }
            set {
                this.genderFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime birthDate {
            get {
                return this.birthDateField;
            }
            set {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified {
            get {
                return this.birthDateFieldSpecified;
            }
            set {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string stateSubscription {
            get {
                return this.stateSubscriptionField;
            }
            set {
                this.stateSubscriptionField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string representativeNm {
            get {
                return this.representativeNmField;
            }
            set {
                this.representativeNmField = value;
            }
        }
        
        /// <remarks/>
        public long customerGroupId {
            get {
                return this.customerGroupIdField;
            }
            set {
                this.customerGroupIdField = value;
            }
        }
        
        /// <remarks/>
        public customerOptIn optIn {
            get {
                return this.optInField;
            }
            set {
                this.optInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optInSpecified {
            get {
                return this.optInFieldSpecified;
            }
            set {
                this.optInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public customerPartnerOptIn partnerOptIn {
            get {
                return this.partnerOptInField;
            }
            set {
                this.partnerOptInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool partnerOptInSpecified {
            get {
                return this.partnerOptInFieldSpecified;
            }
            set {
                this.partnerOptInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public customerSmsOptIn smsOptIn {
            get {
                return this.smsOptInField;
            }
            set {
                this.smsOptInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsOptInSpecified {
            get {
                return this.smsOptInFieldSpecified;
            }
            set {
                this.smsOptInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public customerSmsTrkOptIn smsTrkOptIn {
            get {
                return this.smsTrkOptInField;
            }
            set {
                this.smsTrkOptInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsTrkOptInSpecified {
            get {
                return this.smsTrkOptInFieldSpecified;
            }
            set {
                this.smsTrkOptInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public orderSummaryInfo orderSummaryInfo {
            get {
                return this.orderSummaryInfoField;
            }
            set {
                this.orderSummaryInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("phone", IsNullable=false)]
        public phoneType[] phoneList {
            get {
                return this.phoneListField;
            }
            set {
                this.phoneListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("address", IsNullable=false)]
        public addressType[] addressList {
            get {
                return this.addressListField;
            }
            set {
                this.addressListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("customerLoyalty")]
        public customerLoyalty[] customerLoyalty {
            get {
                return this.customerLoyaltyField;
            }
            set {
                this.customerLoyaltyField = value;
            }
        }
        
        /// <remarks/>
        public string lastVisitedStore {
            get {
                return this.lastVisitedStoreField;
            }
            set {
                this.lastVisitedStoreField = value;
            }
        }
        
        /// <remarks/>
        public string newsletterOptout {
            get {
                return this.newsletterOptoutField;
            }
            set {
                this.newsletterOptoutField = value;
            }
        }
        
        /// <remarks/>
        public string partnerNewsletterOptout {
            get {
                return this.partnerNewsletterOptoutField;
            }
            set {
                this.partnerNewsletterOptoutField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("email", IsNullable=false)]
        public emailType[] extraEmailList {
            get {
                return this.extraEmailListField;
            }
            set {
                this.extraEmailListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum customerCustomerType {
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        PJ,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum customerGender {
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        F,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum customerOptIn {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum customerPartnerOptIn {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum customerSmsOptIn {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum customerSmsTrkOptIn {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accurate.com/acec/Customer")]
    public partial class orderSummaryInfo {
        
        private long orderCountField;
        
        private bool orderCountFieldSpecified;
        
        private decimal orderTotalField;
        
        private bool orderTotalFieldSpecified;
        
        /// <remarks/>
        public long orderCount {
            get {
                return this.orderCountField;
            }
            set {
                this.orderCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderCountSpecified {
            get {
                return this.orderCountFieldSpecified;
            }
            set {
                this.orderCountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal orderTotal {
            get {
                return this.orderTotalField;
            }
            set {
                this.orderTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderTotalSpecified {
            get {
                return this.orderTotalFieldSpecified;
            }
            set {
                this.orderTotalFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accurate.com/acec/Customer")]
    public partial class emailType {
        
        private string emailIdField;
        
        private int emailTpField;
        
        private string emailField;
        
        private string encryptedEmailField;
        
        private int statusField;
        
        private System.DateTime createDateField;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        /// <remarks/>
        public string emailId {
            get {
                return this.emailIdField;
            }
            set {
                this.emailIdField = value;
            }
        }
        
        /// <remarks/>
        public int emailTp {
            get {
                return this.emailTpField;
            }
            set {
                this.emailTpField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string encryptedEmail {
            get {
                return this.encryptedEmailField;
            }
            set {
                this.encryptedEmailField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accurate.com/acec/Customer")]
    public partial class customerLoyalty {
        
        private string affiliationIdField;
        
        private long custLoyaltyIdField;
        
        private string providerIdField;
        
        /// <remarks/>
        public string affiliationId {
            get {
                return this.affiliationIdField;
            }
            set {
                this.affiliationIdField = value;
            }
        }
        
        /// <remarks/>
        public long custLoyaltyId {
            get {
                return this.custLoyaltyIdField;
            }
            set {
                this.custLoyaltyIdField = value;
            }
        }
        
        /// <remarks/>
        public string providerId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accurate.com/acec/Customer")]
    public partial class addressType {
        
        private long addressIdField;
        
        private int addressTpField;
        
        private string streetTypeField;
        
        private int statusField;
        
        private string recipientNmField;
        
        private string addressField;
        
        private string addressNrField;
        
        private string additionalInfoField;
        
        private string quarterField;
        
        private string cityField;
        
        private string stateField;
        
        private string countryIdField;
        
        private string postalCdIntlField;
        
        private string referenceField;
        
        private string friendlyNmField;
        
        private System.DateTime createDateField;
        
        private bool createDateFieldSpecified;
        
        private long postalCdField;
        
        private bool postalCdFieldSpecified;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        private string addressExtra1Field;
        
        private string addressExtra2Field;
        
        private string buildingNmField;
        
        private string floorField;
        
        private string digicodeField;
        
        private addressTypeLift liftField;
        
        private bool liftFieldSpecified;
        
        private addressTypeIntercom intercomField;
        
        private bool intercomFieldSpecified;
        
        /// <remarks/>
        public long addressId {
            get {
                return this.addressIdField;
            }
            set {
                this.addressIdField = value;
            }
        }
        
        /// <remarks/>
        public int addressTp {
            get {
                return this.addressTpField;
            }
            set {
                this.addressTpField = value;
            }
        }
        
        /// <remarks/>
        public string streetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string recipientNm {
            get {
                return this.recipientNmField;
            }
            set {
                this.recipientNmField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string addressNr {
            get {
                return this.addressNrField;
            }
            set {
                this.addressNrField = value;
            }
        }
        
        /// <remarks/>
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
            }
        }
        
        /// <remarks/>
        public string quarter {
            get {
                return this.quarterField;
            }
            set {
                this.quarterField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string countryId {
            get {
                return this.countryIdField;
            }
            set {
                this.countryIdField = value;
            }
        }
        
        /// <remarks/>
        public string postalCdIntl {
            get {
                return this.postalCdIntlField;
            }
            set {
                this.postalCdIntlField = value;
            }
        }
        
        /// <remarks/>
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        public string friendlyNm {
            get {
                return this.friendlyNmField;
            }
            set {
                this.friendlyNmField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createDateSpecified {
            get {
                return this.createDateFieldSpecified;
            }
            set {
                this.createDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public long postalCd {
            get {
                return this.postalCdField;
            }
            set {
                this.postalCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool postalCdSpecified {
            get {
                return this.postalCdFieldSpecified;
            }
            set {
                this.postalCdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string addressExtra1 {
            get {
                return this.addressExtra1Field;
            }
            set {
                this.addressExtra1Field = value;
            }
        }
        
        /// <remarks/>
        public string addressExtra2 {
            get {
                return this.addressExtra2Field;
            }
            set {
                this.addressExtra2Field = value;
            }
        }
        
        /// <remarks/>
        public string buildingNm {
            get {
                return this.buildingNmField;
            }
            set {
                this.buildingNmField = value;
            }
        }
        
        /// <remarks/>
        public string floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        public string digicode {
            get {
                return this.digicodeField;
            }
            set {
                this.digicodeField = value;
            }
        }
        
        /// <remarks/>
        public addressTypeLift lift {
            get {
                return this.liftField;
            }
            set {
                this.liftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool liftSpecified {
            get {
                return this.liftFieldSpecified;
            }
            set {
                this.liftFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public addressTypeIntercom intercom {
            get {
                return this.intercomField;
            }
            set {
                this.intercomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool intercomSpecified {
            get {
                return this.intercomFieldSpecified;
            }
            set {
                this.intercomFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum addressTypeLift {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/Customer")]
    public enum addressTypeIntercom {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        Y,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accurate.com/acec/Customer")]
    public partial class phoneType {
        
        private long phoneIdField;
        
        private int phoneTpField;
        
        private long countryCdField;
        
        private bool countryCdFieldSpecified;
        
        private string areaCdField;
        
        private long phoneNrField;
        
        private bool phoneNrFieldSpecified;
        
        private string encryptedPhoneNrField;
        
        private long extensionField;
        
        private bool extensionFieldSpecified;
        
        private int statusField;
        
        private System.DateTime createDateField;
        
        private System.DateTime updateDateField;
        
        private bool updateDateFieldSpecified;
        
        /// <remarks/>
        public long phoneId {
            get {
                return this.phoneIdField;
            }
            set {
                this.phoneIdField = value;
            }
        }
        
        /// <remarks/>
        public int phoneTp {
            get {
                return this.phoneTpField;
            }
            set {
                this.phoneTpField = value;
            }
        }
        
        /// <remarks/>
        public long countryCd {
            get {
                return this.countryCdField;
            }
            set {
                this.countryCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool countryCdSpecified {
            get {
                return this.countryCdFieldSpecified;
            }
            set {
                this.countryCdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string areaCd {
            get {
                return this.areaCdField;
            }
            set {
                this.areaCdField = value;
            }
        }
        
        /// <remarks/>
        public long phoneNr {
            get {
                return this.phoneNrField;
            }
            set {
                this.phoneNrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool phoneNrSpecified {
            get {
                return this.phoneNrFieldSpecified;
            }
            set {
                this.phoneNrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string encryptedPhoneNr {
            get {
                return this.encryptedPhoneNrField;
            }
            set {
                this.encryptedPhoneNrField = value;
            }
        }
        
        /// <remarks/>
        public long extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool extensionSpecified {
            get {
                return this.extensionFieldSpecified;
            }
            set {
                this.extensionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updateDate {
            get {
                return this.updateDateField;
            }
            set {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateDateSpecified {
            get {
                return this.updateDateFieldSpecified;
            }
            set {
                this.updateDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/CustomerServices")]
    public partial class notifyCustomerCreationResponse {
        
        private string statusField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/CustomerServices")]
    public partial class updateCustomerRequest {
        
        private customer customerField;
        
        private string storeIdField;
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.accurate.com/acec/Customer")]
        public customer customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        public string storeId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/CustomerServices")]
    public partial class updateCustomerResponse {
        
        private string statusField;
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void notifyCustomerCreationCompletedEventHandler(object sender, notifyCustomerCreationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class notifyCustomerCreationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal notifyCustomerCreationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public notifyCustomerCreationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((notifyCustomerCreationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void updateCustomerCompletedEventHandler(object sender, updateCustomerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCustomerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCustomerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public updateCustomerResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((updateCustomerResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591