//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Integradora.ECommerce.Infracommerce.WebServiceEstoque {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="StockServicesBinding", Namespace="http://www.accurate.com/acec/StockServices")]
    public partial class StockServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback setStockOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public StockServices() {
            this.Url = global::Integradora.Biblioteca.Dictionaries.Settings.InfracommerceURL_Stock();
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event setStockCompletedEventHandler setStockCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("setStock", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("setStockResponse", Namespace="http://www.accurate.com/acec/StockServices")]
        public setStockResponse setStock([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.accurate.com/acec/StockServices")] setStockRequest setStockRequest) {
            object[] results = this.Invoke("setStock", new object[] {
                        setStockRequest});
            return ((setStockResponse)(results[0]));
        }
        
        /// <remarks/>
        public void setStockAsync(setStockRequest setStockRequest) {
            this.setStockAsync(setStockRequest, null);
        }
        
        /// <remarks/>
        public void setStockAsync(setStockRequest setStockRequest, object userState) {
            if ((this.setStockOperationCompleted == null)) {
                this.setStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetStockOperationCompleted);
            }
            this.InvokeAsync("setStock", new object[] {
                        setStockRequest}, this.setStockOperationCompleted, userState);
        }
        
        private void OnsetStockOperationCompleted(object arg) {
            if ((this.setStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setStockCompleted(this, new setStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/StockServices")]
    public partial class setStockRequest {
        
        private stock[] stockListField;
        
        private bool orderAccountingFlagField;
        
        private string storeIdField;
        
        public setStockRequest() {
            this.orderAccountingFlagField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Stock", IsNullable=false)]
        public stock[] stockList {
            get {
                return this.stockListField;
            }
            set {
                this.stockListField = value;
            }
        }
        
        /// <remarks/>
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool orderAccountingFlag {
            get {
                return this.orderAccountingFlagField;
            }
            set {
                this.orderAccountingFlagField = value;
            }
        }
        
        /// <remarks/>
        public string storeId {
            get {
                return this.storeIdField;
            }
            set {
                this.storeIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.accurate.com/acec/Stock")]
    public partial class stock {
        
        private string skuIdField;
        
        private int wareHouseIdField;
        
        private bool wareHouseIdFieldSpecified;
        
        private int warehouseCnpjField;
        
        private bool warehouseCnpjFieldSpecified;
        
        private int stockTypeField;
        
        private int leadTimeField;
        
        private int quantityField;
        
        private bool relativeStockFlagField;
        
        private bool relativeStockFlagFieldSpecified;
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private System.DateTime endDateField;
        
        private bool endDateFieldSpecified;
        
        /// <remarks/>
        public string skuId {
            get {
                return this.skuIdField;
            }
            set {
                this.skuIdField = value;
            }
        }
        
        /// <remarks/>
        public int wareHouseId {
            get {
                return this.wareHouseIdField;
            }
            set {
                this.wareHouseIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wareHouseIdSpecified {
            get {
                return this.wareHouseIdFieldSpecified;
            }
            set {
                this.wareHouseIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int warehouseCnpj {
            get {
                return this.warehouseCnpjField;
            }
            set {
                this.warehouseCnpjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool warehouseCnpjSpecified {
            get {
                return this.warehouseCnpjFieldSpecified;
            }
            set {
                this.warehouseCnpjFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int stockType {
            get {
                return this.stockTypeField;
            }
            set {
                this.stockTypeField = value;
            }
        }
        
        /// <remarks/>
        public int leadTime {
            get {
                return this.leadTimeField;
            }
            set {
                this.leadTimeField = value;
            }
        }
        
        /// <remarks/>
        public int quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public bool relativeStockFlag {
            get {
                return this.relativeStockFlagField;
            }
            set {
                this.relativeStockFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool relativeStockFlagSpecified {
            get {
                return this.relativeStockFlagFieldSpecified;
            }
            set {
                this.relativeStockFlagFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified {
            get {
                return this.startDateFieldSpecified;
            }
            set {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool endDateSpecified {
            get {
                return this.endDateFieldSpecified;
            }
            set {
                this.endDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.accurate.com/acec/StockServices")]
    public partial class setStockResponse {
        
        private string resultField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void setStockCompletedEventHandler(object sender, setStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public setStockResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((setStockResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591