//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integradora.Servico.Testes.TesteWebServiceVTiger {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/Integradora.WebServiceVTiger")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseTabelas", Namespace="http://schemas.datacontract.org/2004/07/Integradora.WebServiceVTiger.Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integradora.Servico.Testes.TesteWebServiceVTiger.ItemPedido))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integradora.Servico.Testes.TesteWebServiceVTiger.ParcelaPedido))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido))]
    public partial class BaseTabelas : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DtalteracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DtinclusaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObsintegracaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dtalteracao {
            get {
                return this.DtalteracaoField;
            }
            set {
                if ((this.DtalteracaoField.Equals(value) != true)) {
                    this.DtalteracaoField = value;
                    this.RaisePropertyChanged("Dtalteracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> Dtinclusao {
            get {
                return this.DtinclusaoField;
            }
            set {
                if ((this.DtinclusaoField.Equals(value) != true)) {
                    this.DtinclusaoField = value;
                    this.RaisePropertyChanged("Dtinclusao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Obsintegracao {
            get {
                return this.ObsintegracaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObsintegracaoField, value) != true)) {
                    this.ObsintegracaoField = value;
                    this.RaisePropertyChanged("Obsintegracao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://schemas.datacontract.org/2004/07/Integradora.WebServiceVTiger.Entidades")]
    [System.SerializableAttribute()]
    public partial class Cliente : Integradora.Servico.Testes.TesteWebServiceVTiger.BaseTabelas {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BairroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CEPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CNPJCPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodclienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComplementoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FAXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscricaoestadualField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomefantasiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazaosocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bairro {
            get {
                return this.BairroField;
            }
            set {
                if ((object.ReferenceEquals(this.BairroField, value) != true)) {
                    this.BairroField = value;
                    this.RaisePropertyChanged("Bairro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CEP {
            get {
                return this.CEPField;
            }
            set {
                if ((object.ReferenceEquals(this.CEPField, value) != true)) {
                    this.CEPField = value;
                    this.RaisePropertyChanged("CEP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CNPJCPF {
            get {
                return this.CNPJCPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CNPJCPFField, value) != true)) {
                    this.CNPJCPFField = value;
                    this.RaisePropertyChanged("CNPJCPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cidade {
            get {
                return this.CidadeField;
            }
            set {
                if ((object.ReferenceEquals(this.CidadeField, value) != true)) {
                    this.CidadeField = value;
                    this.RaisePropertyChanged("Cidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codcliente {
            get {
                return this.CodclienteField;
            }
            set {
                if ((this.CodclienteField.Equals(value) != true)) {
                    this.CodclienteField = value;
                    this.RaisePropertyChanged("Codcliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento {
            get {
                return this.ComplementoField;
            }
            set {
                if ((object.ReferenceEquals(this.ComplementoField, value) != true)) {
                    this.ComplementoField = value;
                    this.RaisePropertyChanged("Complemento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FAX {
            get {
                return this.FAXField;
            }
            set {
                if ((object.ReferenceEquals(this.FAXField, value) != true)) {
                    this.FAXField = value;
                    this.RaisePropertyChanged("FAX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inscricaoestadual {
            get {
                return this.InscricaoestadualField;
            }
            set {
                if ((object.ReferenceEquals(this.InscricaoestadualField, value) != true)) {
                    this.InscricaoestadualField = value;
                    this.RaisePropertyChanged("Inscricaoestadual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nomefantasia {
            get {
                return this.NomefantasiaField;
            }
            set {
                if ((object.ReferenceEquals(this.NomefantasiaField, value) != true)) {
                    this.NomefantasiaField = value;
                    this.RaisePropertyChanged("Nomefantasia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Razaosocial {
            get {
                return this.RazaosocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazaosocialField, value) != true)) {
                    this.RazaosocialField = value;
                    this.RaisePropertyChanged("Razaosocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefone {
            get {
                return this.TelefoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneField, value) != true)) {
                    this.TelefoneField = value;
                    this.RaisePropertyChanged("Telefone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemPedido", Namespace="http://schemas.datacontract.org/2004/07/Integradora.WebServiceVTiger.Entidades")]
    [System.SerializableAttribute()]
    public partial class ItemPedido : Integradora.Servico.Testes.TesteWebServiceVTiger.BaseTabelas {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CodprodutoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumitemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PercentualdescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecotabelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecovendaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal QuantidadeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Codproduto {
            get {
                return this.CodprodutoField;
            }
            set {
                if ((this.CodprodutoField.Equals(value) != true)) {
                    this.CodprodutoField = value;
                    this.RaisePropertyChanged("Codproduto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numitem {
            get {
                return this.NumitemField;
            }
            set {
                if ((this.NumitemField.Equals(value) != true)) {
                    this.NumitemField = value;
                    this.RaisePropertyChanged("Numitem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Percentualdesconto {
            get {
                return this.PercentualdescontoField;
            }
            set {
                if ((this.PercentualdescontoField.Equals(value) != true)) {
                    this.PercentualdescontoField = value;
                    this.RaisePropertyChanged("Percentualdesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precotabela {
            get {
                return this.PrecotabelaField;
            }
            set {
                if ((this.PrecotabelaField.Equals(value) != true)) {
                    this.PrecotabelaField = value;
                    this.RaisePropertyChanged("Precotabela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precovenda {
            get {
                return this.PrecovendaField;
            }
            set {
                if ((this.PrecovendaField.Equals(value) != true)) {
                    this.PrecovendaField = value;
                    this.RaisePropertyChanged("Precovenda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParcelaPedido", Namespace="http://schemas.datacontract.org/2004/07/Integradora.WebServiceVTiger.Entidades")]
    [System.SerializableAttribute()]
    public partial class ParcelaPedido : Integradora.Servico.Testes.TesteWebServiceVTiger.BaseTabelas {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CodAutorizacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtvencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NSUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumparcelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CodAutorizacao {
            get {
                return this.CodAutorizacaoField;
            }
            set {
                if ((this.CodAutorizacaoField.Equals(value) != true)) {
                    this.CodAutorizacaoField = value;
                    this.RaisePropertyChanged("CodAutorizacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dtvencimento {
            get {
                return this.DtvencimentoField;
            }
            set {
                if ((this.DtvencimentoField.Equals(value) != true)) {
                    this.DtvencimentoField = value;
                    this.RaisePropertyChanged("Dtvencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NSU {
            get {
                return this.NSUField;
            }
            set {
                if ((object.ReferenceEquals(this.NSUField, value) != true)) {
                    this.NSUField = value;
                    this.RaisePropertyChanged("NSU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Numparcela {
            get {
                return this.NumparcelaField;
            }
            set {
                if ((this.NumparcelaField.Equals(value) != true)) {
                    this.NumparcelaField = value;
                    this.RaisePropertyChanged("Numparcela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://schemas.datacontract.org/2004/07/Integradora.WebServiceVTiger.Entidades")]
    [System.SerializableAttribute()]
    public partial class Pedido : Integradora.Servico.Testes.TesteWebServiceVTiger.BaseTabelas {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CodvendedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtemissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DtentregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Integradora.Servico.Testes.TesteWebServiceVTiger.ItemPedido[] ItensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NumpedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Integradora.Servico.Testes.TesteWebServiceVTiger.ParcelaPedido[] ParcelasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValordescontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValorfreteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ValortotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Codvendedor {
            get {
                return this.CodvendedorField;
            }
            set {
                if ((this.CodvendedorField.Equals(value) != true)) {
                    this.CodvendedorField = value;
                    this.RaisePropertyChanged("Codvendedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dtemissao {
            get {
                return this.DtemissaoField;
            }
            set {
                if ((this.DtemissaoField.Equals(value) != true)) {
                    this.DtemissaoField = value;
                    this.RaisePropertyChanged("Dtemissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Dtentrega {
            get {
                return this.DtentregaField;
            }
            set {
                if ((this.DtentregaField.Equals(value) != true)) {
                    this.DtentregaField = value;
                    this.RaisePropertyChanged("Dtentrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Integradora.Servico.Testes.TesteWebServiceVTiger.ItemPedido[] Itens {
            get {
                return this.ItensField;
            }
            set {
                if ((object.ReferenceEquals(this.ItensField, value) != true)) {
                    this.ItensField = value;
                    this.RaisePropertyChanged("Itens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Numpedido {
            get {
                return this.NumpedidoField;
            }
            set {
                if ((this.NumpedidoField.Equals(value) != true)) {
                    this.NumpedidoField = value;
                    this.RaisePropertyChanged("Numpedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observacao {
            get {
                return this.ObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacaoField, value) != true)) {
                    this.ObservacaoField = value;
                    this.RaisePropertyChanged("Observacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Integradora.Servico.Testes.TesteWebServiceVTiger.ParcelaPedido[] Parcelas {
            get {
                return this.ParcelasField;
            }
            set {
                if ((object.ReferenceEquals(this.ParcelasField, value) != true)) {
                    this.ParcelasField = value;
                    this.RaisePropertyChanged("Parcelas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valordesconto {
            get {
                return this.ValordescontoField;
            }
            set {
                if ((this.ValordescontoField.Equals(value) != true)) {
                    this.ValordescontoField = value;
                    this.RaisePropertyChanged("Valordesconto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valorfrete {
            get {
                return this.ValorfreteField;
            }
            set {
                if ((this.ValorfreteField.Equals(value) != true)) {
                    this.ValorfreteField = value;
                    this.RaisePropertyChanged("Valorfrete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Valortotal {
            get {
                return this.ValortotalField;
            }
            set {
                if ((this.ValortotalField.Equals(value) != true)) {
                    this.ValortotalField = value;
                    this.RaisePropertyChanged("Valortotal");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TesteWebServiceVTiger.IWebServiceVTiger")]
    public interface IWebServiceVTiger {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/GetData", ReplyAction="http://tempuri.org/IWebServiceVTiger/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/GetData", ReplyAction="http://tempuri.org/IWebServiceVTiger/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWebServiceVTiger/GetDataUsingDataContractResponse")]
        Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType GetDataUsingDataContract(Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IWebServiceVTiger/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType> GetDataUsingDataContractAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVenda", ReplyAction="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVendaResponse")]
        string EnviarPedidoVenda(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVenda", ReplyAction="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVendaResponse")]
        System.Threading.Tasks.Task<string> EnviarPedidoVendaAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVendaJson", ReplyAction="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVendaJsonResponse")]
        string EnviarPedidoVendaJson(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVendaJson", ReplyAction="http://tempuri.org/IWebServiceVTiger/EnviarPedidoVendaJsonResponse")]
        System.Threading.Tasks.Task<string> EnviarPedidoVendaJsonAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/EnviarCliente", ReplyAction="http://tempuri.org/IWebServiceVTiger/EnviarClienteResponse")]
        string EnviarCliente(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/EnviarCliente", ReplyAction="http://tempuri.org/IWebServiceVTiger/EnviarClienteResponse")]
        System.Threading.Tasks.Task<string> EnviarClienteAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/InserirClienteJson", ReplyAction="http://tempuri.org/IWebServiceVTiger/InserirClienteJsonResponse")]
        string InserirClienteJson(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebServiceVTiger/InserirClienteJson", ReplyAction="http://tempuri.org/IWebServiceVTiger/InserirClienteJsonResponse")]
        System.Threading.Tasks.Task<string> InserirClienteJsonAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebServiceVTigerChannel : Integradora.Servico.Testes.TesteWebServiceVTiger.IWebServiceVTiger, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceVTigerClient : System.ServiceModel.ClientBase<Integradora.Servico.Testes.TesteWebServiceVTiger.IWebServiceVTiger>, Integradora.Servico.Testes.TesteWebServiceVTiger.IWebServiceVTiger {
        
        public WebServiceVTigerClient() {
        }
        
        public WebServiceVTigerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceVTigerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVTigerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceVTigerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType GetDataUsingDataContract(Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType> GetDataUsingDataContractAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public string EnviarPedidoVenda(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido) {
            return base.Channel.EnviarPedidoVenda(pedido);
        }
        
        public System.Threading.Tasks.Task<string> EnviarPedidoVendaAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido) {
            return base.Channel.EnviarPedidoVendaAsync(pedido);
        }
        
        public string EnviarPedidoVendaJson(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido) {
            return base.Channel.EnviarPedidoVendaJson(pedido);
        }
        
        public System.Threading.Tasks.Task<string> EnviarPedidoVendaJsonAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Pedido pedido) {
            return base.Channel.EnviarPedidoVendaJsonAsync(pedido);
        }
        
        public string EnviarCliente(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente) {
            return base.Channel.EnviarCliente(cliente);
        }
        
        public System.Threading.Tasks.Task<string> EnviarClienteAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente) {
            return base.Channel.EnviarClienteAsync(cliente);
        }
        
        public string InserirClienteJson(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente) {
            return base.Channel.InserirClienteJson(cliente);
        }
        
        public System.Threading.Tasks.Task<string> InserirClienteJsonAsync(Integradora.Servico.Testes.TesteWebServiceVTiger.Cliente cliente) {
            return base.Channel.InserirClienteJsonAsync(cliente);
        }
    }
}
