//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace Integradora.ECommerce.FBits.SyncPedidoVenda {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncPedidoVendaSoap", Namespace="http://tempuri.org/")]
    public partial class SyncPedidoVenda : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompleteBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback CompleteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SyncPedidoVenda() {
            this.Url = global::Integradora.ECommerce.FBits.Properties.Settings.Default.Integradora_ECommerce_FBits_SyncPedidoVenda;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetItemsCompletedEventHandler GetItemsCompleted;
        
        /// <remarks/>
        public event SelectCompletedEventHandler SelectCompleted;
        
        /// <remarks/>
        public event CompleteBatchCompletedEventHandler CompleteBatchCompleted;
        
        /// <remarks/>
        public event CompleteCompletedEventHandler CompleteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItems", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoPedidoVendaInfo[] GetItems(string token) {
            object[] results = this.Invoke("GetItems", new object[] {
                        token});
            return ((IntegracaoPedidoVendaInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsAsync(string token) {
            this.GetItemsAsync(token, null);
        }
        
        /// <remarks/>
        public void GetItemsAsync(string token, object userState) {
            if ((this.GetItemsOperationCompleted == null)) {
                this.GetItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsOperationCompleted);
            }
            this.InvokeAsync("GetItems", new object[] {
                        token}, this.GetItemsOperationCompleted, userState);
        }
        
        private void OnGetItemsOperationCompleted(object arg) {
            if ((this.GetItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCompleted(this, new GetItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Select", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IntegracaoPedidoVendaInfo Select(string token, long pedidoId) {
            object[] results = this.Invoke("Select", new object[] {
                        token,
                        pedidoId});
            return ((IntegracaoPedidoVendaInfo)(results[0]));
        }
        
        /// <remarks/>
        public void SelectAsync(string token, long pedidoId) {
            this.SelectAsync(token, pedidoId, null);
        }
        
        /// <remarks/>
        public void SelectAsync(string token, long pedidoId, object userState) {
            if ((this.SelectOperationCompleted == null)) {
                this.SelectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectOperationCompleted);
            }
            this.InvokeAsync("Select", new object[] {
                        token,
                        pedidoId}, this.SelectOperationCompleted, userState);
        }
        
        private void OnSelectOperationCompleted(object arg) {
            if ((this.SelectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectCompleted(this, new SelectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CompleteBatch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CompleteBatch(string token, long[] pedidoIdArray) {
            object[] results = this.Invoke("CompleteBatch", new object[] {
                        token,
                        pedidoIdArray});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CompleteBatchAsync(string token, long[] pedidoIdArray) {
            this.CompleteBatchAsync(token, pedidoIdArray, null);
        }
        
        /// <remarks/>
        public void CompleteBatchAsync(string token, long[] pedidoIdArray, object userState) {
            if ((this.CompleteBatchOperationCompleted == null)) {
                this.CompleteBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompleteBatchOperationCompleted);
            }
            this.InvokeAsync("CompleteBatch", new object[] {
                        token,
                        pedidoIdArray}, this.CompleteBatchOperationCompleted, userState);
        }
        
        private void OnCompleteBatchOperationCompleted(object arg) {
            if ((this.CompleteBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompleteBatchCompleted(this, new CompleteBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Complete", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Complete(string token, long pedidoId) {
            object[] results = this.Invoke("Complete", new object[] {
                        token,
                        pedidoId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CompleteAsync(string token, long pedidoId) {
            this.CompleteAsync(token, pedidoId, null);
        }
        
        /// <remarks/>
        public void CompleteAsync(string token, long pedidoId, object userState) {
            if ((this.CompleteOperationCompleted == null)) {
                this.CompleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompleteOperationCompleted);
            }
            this.InvokeAsync("Complete", new object[] {
                        token,
                        pedidoId}, this.CompleteOperationCompleted, userState);
        }
        
        private void OnCompleteOperationCompleted(object arg) {
            if ((this.CompleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompleteCompleted(this, new CompleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IntegracaoPedidoVendaInfo {
        
        private long pedidoIdField;
        
        private long usuarioIdField;
        
        private System.DateTime dataPedidoField;
        
        private string nomeDestinoField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private string cepField;
        
        private string rgField;
        
        private int parcelasField;
        
        private decimal valorFreteField;
        
        private decimal valorFreteEmpresaField;
        
        private long transportadoraFreteField;
        
        private System.Nullable<System.DateTime> dataEntregaField;
        
        private string entregaAgendadaPeriodoField;
        
        private decimal valorPedidoField;
        
        private string ipField;
        
        private int prazoEnvioField;
        
        private string linhaDigitalBoletoField;
        
        private string numeroCupomDescontoField;
        
        private decimal valorCupomDescontoField;
        
        private int statusField;
        
        private decimal subtotalField;
        
        private decimal valorJurosField;
        
        private decimal valorParcelasField;
        
        private decimal valorServicosField;
        
        private int parceiroIdField;
        
        private int tabelaPrecoIdField;
        
        private IntegracaoUsuarioInfo usuarioField;
        
        private IntegracaoPedidoProdutoInfo[] itensField;
        
        private PedidoPagamentoInfo[] formasPagamentoField;
        
        private IntegracaoAssinaturaInfo assinaturaField;
        
        /// <remarks/>
        public long PedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        public long UsuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataPedido {
            get {
                return this.dataPedidoField;
            }
            set {
                this.dataPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeDestino {
            get {
                return this.nomeDestinoField;
            }
            set {
                this.nomeDestinoField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public int Parcelas {
            get {
                return this.parcelasField;
            }
            set {
                this.parcelasField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorFrete {
            get {
                return this.valorFreteField;
            }
            set {
                this.valorFreteField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorFreteEmpresa {
            get {
                return this.valorFreteEmpresaField;
            }
            set {
                this.valorFreteEmpresaField = value;
            }
        }
        
        /// <remarks/>
        public long TransportadoraFrete {
            get {
                return this.transportadoraFreteField;
            }
            set {
                this.transportadoraFreteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataEntrega {
            get {
                return this.dataEntregaField;
            }
            set {
                this.dataEntregaField = value;
            }
        }
        
        /// <remarks/>
        public string EntregaAgendadaPeriodo {
            get {
                return this.entregaAgendadaPeriodoField;
            }
            set {
                this.entregaAgendadaPeriodoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorPedido {
            get {
                return this.valorPedidoField;
            }
            set {
                this.valorPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string Ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        public int PrazoEnvio {
            get {
                return this.prazoEnvioField;
            }
            set {
                this.prazoEnvioField = value;
            }
        }
        
        /// <remarks/>
        public string LinhaDigitalBoleto {
            get {
                return this.linhaDigitalBoletoField;
            }
            set {
                this.linhaDigitalBoletoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCupomDesconto {
            get {
                return this.numeroCupomDescontoField;
            }
            set {
                this.numeroCupomDescontoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorCupomDesconto {
            get {
                return this.valorCupomDescontoField;
            }
            set {
                this.valorCupomDescontoField = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public decimal Subtotal {
            get {
                return this.subtotalField;
            }
            set {
                this.subtotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorJuros {
            get {
                return this.valorJurosField;
            }
            set {
                this.valorJurosField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorParcelas {
            get {
                return this.valorParcelasField;
            }
            set {
                this.valorParcelasField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorServicos {
            get {
                return this.valorServicosField;
            }
            set {
                this.valorServicosField = value;
            }
        }
        
        /// <remarks/>
        public int ParceiroId {
            get {
                return this.parceiroIdField;
            }
            set {
                this.parceiroIdField = value;
            }
        }
        
        /// <remarks/>
        public int TabelaPrecoId {
            get {
                return this.tabelaPrecoIdField;
            }
            set {
                this.tabelaPrecoIdField = value;
            }
        }
        
        /// <remarks/>
        public IntegracaoUsuarioInfo Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <remarks/>
        public IntegracaoPedidoProdutoInfo[] Itens {
            get {
                return this.itensField;
            }
            set {
                this.itensField = value;
            }
        }
        
        /// <remarks/>
        public PedidoPagamentoInfo[] FormasPagamento {
            get {
                return this.formasPagamentoField;
            }
            set {
                this.formasPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public IntegracaoAssinaturaInfo Assinatura {
            get {
                return this.assinaturaField;
            }
            set {
                this.assinaturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IntegracaoUsuarioInfo {
        
        private long usuarioIdField;
        
        private int ecommerceIdField;
        
        private int tipoPessoaIdField;
        
        private int origemContatoIdField;
        
        private System.Nullable<long> enderecoResidencialIdField;
        
        private System.Nullable<long> enderecoEntregaIdField;
        
        private int tipoSexoIdField;
        
        private System.Nullable<int> formaPagamentoIdField;
        
        private System.Nullable<int> tipoPreferenciaUsuarioIdField;
        
        private string nomeField;
        
        private string cPFField;
        
        private string emailField;
        
        private string rgField;
        
        private string orgaoEmissorField;
        
        private string nomeMaeField;
        
        private string telefoneResidencialField;
        
        private string telefoneCelularField;
        
        private string telefoneComercialField;
        
        private System.Nullable<System.DateTime> dataNascimentoField;
        
        private string razaoSocialField;
        
        private string cNPJField;
        
        private string inscricaoEstadualField;
        
        private string responsavelField;
        
        private System.DateTime dataCriacaoField;
        
        private System.Nullable<System.DateTime> dataAtualizacaoField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private string cEPField;
        
        private int parceiroIDField;
        
        private IntegracaoNewsletterInfo dadosNewsletterField;
        
        /// <remarks/>
        public long UsuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
            }
        }
        
        /// <remarks/>
        public int EcommerceId {
            get {
                return this.ecommerceIdField;
            }
            set {
                this.ecommerceIdField = value;
            }
        }
        
        /// <remarks/>
        public int TipoPessoaId {
            get {
                return this.tipoPessoaIdField;
            }
            set {
                this.tipoPessoaIdField = value;
            }
        }
        
        /// <remarks/>
        public int OrigemContatoId {
            get {
                return this.origemContatoIdField;
            }
            set {
                this.origemContatoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> EnderecoResidencialId {
            get {
                return this.enderecoResidencialIdField;
            }
            set {
                this.enderecoResidencialIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> EnderecoEntregaId {
            get {
                return this.enderecoEntregaIdField;
            }
            set {
                this.enderecoEntregaIdField = value;
            }
        }
        
        /// <remarks/>
        public int TipoSexoId {
            get {
                return this.tipoSexoIdField;
            }
            set {
                this.tipoSexoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> FormaPagamentoId {
            get {
                return this.formaPagamentoIdField;
            }
            set {
                this.formaPagamentoIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> TipoPreferenciaUsuarioId {
            get {
                return this.tipoPreferenciaUsuarioIdField;
            }
            set {
                this.tipoPreferenciaUsuarioIdField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public string OrgaoEmissor {
            get {
                return this.orgaoEmissorField;
            }
            set {
                this.orgaoEmissorField = value;
            }
        }
        
        /// <remarks/>
        public string NomeMae {
            get {
                return this.nomeMaeField;
            }
            set {
                this.nomeMaeField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneResidencial {
            get {
                return this.telefoneResidencialField;
            }
            set {
                this.telefoneResidencialField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneCelular {
            get {
                return this.telefoneCelularField;
            }
            set {
                this.telefoneCelularField = value;
            }
        }
        
        /// <remarks/>
        public string TelefoneComercial {
            get {
                return this.telefoneComercialField;
            }
            set {
                this.telefoneComercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataNascimento {
            get {
                return this.dataNascimentoField;
            }
            set {
                this.dataNascimentoField = value;
            }
        }
        
        /// <remarks/>
        public string RazaoSocial {
            get {
                return this.razaoSocialField;
            }
            set {
                this.razaoSocialField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string InscricaoEstadual {
            get {
                return this.inscricaoEstadualField;
            }
            set {
                this.inscricaoEstadualField = value;
            }
        }
        
        /// <remarks/>
        public string Responsavel {
            get {
                return this.responsavelField;
            }
            set {
                this.responsavelField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> DataAtualizacao {
            get {
                return this.dataAtualizacaoField;
            }
            set {
                this.dataAtualizacaoField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string Numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
            }
        }
        
        /// <remarks/>
        public string CEP {
            get {
                return this.cEPField;
            }
            set {
                this.cEPField = value;
            }
        }
        
        /// <remarks/>
        public int ParceiroID {
            get {
                return this.parceiroIDField;
            }
            set {
                this.parceiroIDField = value;
            }
        }
        
        /// <remarks/>
        public IntegracaoNewsletterInfo DadosNewsletter {
            get {
                return this.dadosNewsletterField;
            }
            set {
                this.dadosNewsletterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IntegracaoNewsletterInfo {
        
        private long integracaoNewsletterIdField;
        
        private long usuarioIdField;
        
        private string nomeField;
        
        private string emailField;
        
        private System.DateTime dataCadastroField;
        
        private bool statusField;
        
        private string sexoField;
        
        private bool doubleOptInValidoField;
        
        private System.DateTime dataAceitacaoOptInField;
        
        private string iPAceitacaoOptInField;
        
        /// <remarks/>
        public long IntegracaoNewsletterId {
            get {
                return this.integracaoNewsletterIdField;
            }
            set {
                this.integracaoNewsletterIdField = value;
            }
        }
        
        /// <remarks/>
        public long UsuarioId {
            get {
                return this.usuarioIdField;
            }
            set {
                this.usuarioIdField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCadastro {
            get {
                return this.dataCadastroField;
            }
            set {
                this.dataCadastroField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string Sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public bool DoubleOptInValido {
            get {
                return this.doubleOptInValidoField;
            }
            set {
                this.doubleOptInValidoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataAceitacaoOptIn {
            get {
                return this.dataAceitacaoOptInField;
            }
            set {
                this.dataAceitacaoOptInField = value;
            }
        }
        
        /// <remarks/>
        public string IPAceitacaoOptIn {
            get {
                return this.iPAceitacaoOptInField;
            }
            set {
                this.iPAceitacaoOptInField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IntegracaoAssinaturaInfo {
        
        private long pedidoIdField;
        
        private long assinaturaIdField;
        
        private long grupoAssinaturaIdField;
        
        private string grupoAssinaturaNomeField;
        
        private string tipoPeriodoField;
        
        private int tempoPeriodoField;
        
        private decimal percentualDescontoField;
        
        /// <remarks/>
        public long PedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        public long AssinaturaId {
            get {
                return this.assinaturaIdField;
            }
            set {
                this.assinaturaIdField = value;
            }
        }
        
        /// <remarks/>
        public long GrupoAssinaturaId {
            get {
                return this.grupoAssinaturaIdField;
            }
            set {
                this.grupoAssinaturaIdField = value;
            }
        }
        
        /// <remarks/>
        public string GrupoAssinaturaNome {
            get {
                return this.grupoAssinaturaNomeField;
            }
            set {
                this.grupoAssinaturaNomeField = value;
            }
        }
        
        /// <remarks/>
        public string TipoPeriodo {
            get {
                return this.tipoPeriodoField;
            }
            set {
                this.tipoPeriodoField = value;
            }
        }
        
        /// <remarks/>
        public int TempoPeriodo {
            get {
                return this.tempoPeriodoField;
            }
            set {
                this.tempoPeriodoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PercentualDesconto {
            get {
                return this.percentualDescontoField;
            }
            set {
                this.percentualDescontoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class PedidoPagamentoInfo {
        
        private long pedidoPagamentoIdField;
        
        private long pedidoIdField;
        
        private int formaPagamentoIdField;
        
        private int numeroParcelasField;
        
        private decimal valorParcelaField;
        
        private decimal valorDescontoField;
        
        private decimal valorJurosField;
        
        private decimal valorTotalField;
        
        private string numeroCartaoCreditoField;
        
        private string nomeCartaoCreditoField;
        
        private string codigoSegurancaCartaoCreditoField;
        
        private System.Nullable<System.DateTime> validadeCartaoCreditoField;
        
        /// <remarks/>
        public long PedidoPagamentoId {
            get {
                return this.pedidoPagamentoIdField;
            }
            set {
                this.pedidoPagamentoIdField = value;
            }
        }
        
        /// <remarks/>
        public long PedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        public int FormaPagamentoId {
            get {
                return this.formaPagamentoIdField;
            }
            set {
                this.formaPagamentoIdField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroParcelas {
            get {
                return this.numeroParcelasField;
            }
            set {
                this.numeroParcelasField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorParcela {
            get {
                return this.valorParcelaField;
            }
            set {
                this.valorParcelaField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorDesconto {
            get {
                return this.valorDescontoField;
            }
            set {
                this.valorDescontoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorJuros {
            get {
                return this.valorJurosField;
            }
            set {
                this.valorJurosField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorTotal {
            get {
                return this.valorTotalField;
            }
            set {
                this.valorTotalField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroCartaoCredito {
            get {
                return this.numeroCartaoCreditoField;
            }
            set {
                this.numeroCartaoCreditoField = value;
            }
        }
        
        /// <remarks/>
        public string NomeCartaoCredito {
            get {
                return this.nomeCartaoCreditoField;
            }
            set {
                this.nomeCartaoCreditoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoSegurancaCartaoCredito {
            get {
                return this.codigoSegurancaCartaoCreditoField;
            }
            set {
                this.codigoSegurancaCartaoCreditoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> ValidadeCartaoCredito {
            get {
                return this.validadeCartaoCreditoField;
            }
            set {
                this.validadeCartaoCreditoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IntegracaoPedidoProdutoServicoInfo {
        
        private int servicoIdField;
        
        private string descricaoField;
        
        private string descricaoPrecoField;
        
        private int idPrecoField;
        
        private string nomeField;
        
        private decimal precoServicoField;
        
        private decimal precoServicoTotalField;
        
        private long pedidoProdutoIdField;
        
        private long pedidoProdutoAconteceServicoIdField;
        
        private int quantidadeField;
        
        private string tempoField;
        
        private string validadorField;
        
        private string contratoGarantiaField;
        
        /// <remarks/>
        public int ServicoId {
            get {
                return this.servicoIdField;
            }
            set {
                this.servicoIdField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoPreco {
            get {
                return this.descricaoPrecoField;
            }
            set {
                this.descricaoPrecoField = value;
            }
        }
        
        /// <remarks/>
        public int IdPreco {
            get {
                return this.idPrecoField;
            }
            set {
                this.idPrecoField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecoServico {
            get {
                return this.precoServicoField;
            }
            set {
                this.precoServicoField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecoServicoTotal {
            get {
                return this.precoServicoTotalField;
            }
            set {
                this.precoServicoTotalField = value;
            }
        }
        
        /// <remarks/>
        public long PedidoProdutoId {
            get {
                return this.pedidoProdutoIdField;
            }
            set {
                this.pedidoProdutoIdField = value;
            }
        }
        
        /// <remarks/>
        public long PedidoProdutoAconteceServicoId {
            get {
                return this.pedidoProdutoAconteceServicoIdField;
            }
            set {
                this.pedidoProdutoAconteceServicoIdField = value;
            }
        }
        
        /// <remarks/>
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Tempo {
            get {
                return this.tempoField;
            }
            set {
                this.tempoField = value;
            }
        }
        
        /// <remarks/>
        public string Validador {
            get {
                return this.validadorField;
            }
            set {
                this.validadorField = value;
            }
        }
        
        /// <remarks/>
        public string ContratoGarantia {
            get {
                return this.contratoGarantiaField;
            }
            set {
                this.contratoGarantiaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IntegracaoPedidoProdutoAtributoInfo {
        
        private string nomeField;
        
        private string valorField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class IntegracaoPedidoProdutoInfo {
        
        private long pedidoIdField;
        
        private long produtoVarianteIdField;
        
        private long comboField;
        
        private string sKUField;
        
        private string nomeField;
        
        private string descricaoField;
        
        private double pesoUnitarioField;
        
        private double pesoTotalField;
        
        private decimal precoUnitarioField;
        
        private decimal preco_VendaField;
        
        private decimal precoRateadoField;
        
        private decimal valorJurosField;
        
        private System.DateTime dataCriacaoField;
        
        private System.DateTime dataAtualizacaoField;
        
        private int produtoQuantidadeField;
        
        private string urlImagemField;
        
        private string tipoField;
        
        private System.Nullable<long> pedidoProdutoIdField;
        
        private bool brindeField;
        
        private IntegracaoPedidoProdutoAtributoInfo[] atributosField;
        
        private IntegracaoPedidoProdutoServicoInfo[] servicosField;
        
        /// <remarks/>
        public long PedidoId {
            get {
                return this.pedidoIdField;
            }
            set {
                this.pedidoIdField = value;
            }
        }
        
        /// <remarks/>
        public long ProdutoVarianteId {
            get {
                return this.produtoVarianteIdField;
            }
            set {
                this.produtoVarianteIdField = value;
            }
        }
        
        /// <remarks/>
        public long Combo {
            get {
                return this.comboField;
            }
            set {
                this.comboField = value;
            }
        }
        
        /// <remarks/>
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
            }
        }
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
            }
        }
        
        /// <remarks/>
        public double PesoUnitario {
            get {
                return this.pesoUnitarioField;
            }
            set {
                this.pesoUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public double PesoTotal {
            get {
                return this.pesoTotalField;
            }
            set {
                this.pesoTotalField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecoUnitario {
            get {
                return this.precoUnitarioField;
            }
            set {
                this.precoUnitarioField = value;
            }
        }
        
        /// <remarks/>
        public decimal Preco_Venda {
            get {
                return this.preco_VendaField;
            }
            set {
                this.preco_VendaField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrecoRateado {
            get {
                return this.precoRateadoField;
            }
            set {
                this.precoRateadoField = value;
            }
        }
        
        /// <remarks/>
        public decimal ValorJuros {
            get {
                return this.valorJurosField;
            }
            set {
                this.valorJurosField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataCriacao {
            get {
                return this.dataCriacaoField;
            }
            set {
                this.dataCriacaoField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DataAtualizacao {
            get {
                return this.dataAtualizacaoField;
            }
            set {
                this.dataAtualizacaoField = value;
            }
        }
        
        /// <remarks/>
        public int ProdutoQuantidade {
            get {
                return this.produtoQuantidadeField;
            }
            set {
                this.produtoQuantidadeField = value;
            }
        }
        
        /// <remarks/>
        public string UrlImagem {
            get {
                return this.urlImagemField;
            }
            set {
                this.urlImagemField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> PedidoProdutoId {
            get {
                return this.pedidoProdutoIdField;
            }
            set {
                this.pedidoProdutoIdField = value;
            }
        }
        
        /// <remarks/>
        public bool Brinde {
            get {
                return this.brindeField;
            }
            set {
                this.brindeField = value;
            }
        }
        
        /// <remarks/>
        public IntegracaoPedidoProdutoAtributoInfo[] Atributos {
            get {
                return this.atributosField;
            }
            set {
                this.atributosField = value;
            }
        }
        
        /// <remarks/>
        public IntegracaoPedidoProdutoServicoInfo[] Servicos {
            get {
                return this.servicosField;
            }
            set {
                this.servicosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetItemsCompletedEventHandler(object sender, GetItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoPedidoVendaInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoPedidoVendaInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SelectCompletedEventHandler(object sender, SelectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IntegracaoPedidoVendaInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IntegracaoPedidoVendaInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CompleteBatchCompletedEventHandler(object sender, CompleteBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompleteBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompleteBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void CompleteCompletedEventHandler(object sender, CompleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CompleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591