//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34003.
// 
#pragma warning disable 1591

namespace Integradora.ECommerce.UseAll.Api {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSoap", Namespace="http://tempuri.org/")]
    public partial class WS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Insere_OutrasCob_UCOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insere_ConsumidorOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pagar_FaturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Estornar_Pagamento_FaturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insere_OutrasCob_UC_HistOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insere_Consumidor_NovoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Atualiza_Consumidor_NovoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS() {
            this.Url = Integradora.Biblioteca.Dictionaries.Settings.UseAll_Webservice();
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Insere_OutrasCob_UCCompletedEventHandler Insere_OutrasCob_UCCompleted;
        
        /// <remarks/>
        public event Insere_ConsumidorCompletedEventHandler Insere_ConsumidorCompleted;
        
        /// <remarks/>
        public event Pagar_FaturaCompletedEventHandler Pagar_FaturaCompleted;
        
        /// <remarks/>
        public event Estornar_Pagamento_FaturaCompletedEventHandler Estornar_Pagamento_FaturaCompleted;
        
        /// <remarks/>
        public event Insere_OutrasCob_UC_HistCompletedEventHandler Insere_OutrasCob_UC_HistCompleted;
        
        /// <remarks/>
        public event Insere_Consumidor_NovoCompletedEventHandler Insere_Consumidor_NovoCompleted;
        
        /// <remarks/>
        public event Atualiza_Consumidor_NovoCompletedEventHandler Atualiza_Consumidor_NovoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insere_OutrasCob_UC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insere_OutrasCob_UC(long anidzona, long anidconta, long aniditem, long anmesfatura, long ananofatura, string addatalancto, decimal anvalor, string asideverest) {
            object[] results = this.Invoke("Insere_OutrasCob_UC", new object[] {
                        anidzona,
                        anidconta,
                        aniditem,
                        anmesfatura,
                        ananofatura,
                        addatalancto,
                        anvalor,
                        asideverest});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insere_OutrasCob_UCAsync(long anidzona, long anidconta, long aniditem, long anmesfatura, long ananofatura, string addatalancto, decimal anvalor, string asideverest) {
            this.Insere_OutrasCob_UCAsync(anidzona, anidconta, aniditem, anmesfatura, ananofatura, addatalancto, anvalor, asideverest, null);
        }
        
        /// <remarks/>
        public void Insere_OutrasCob_UCAsync(long anidzona, long anidconta, long aniditem, long anmesfatura, long ananofatura, string addatalancto, decimal anvalor, string asideverest, object userState) {
            if ((this.Insere_OutrasCob_UCOperationCompleted == null)) {
                this.Insere_OutrasCob_UCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsere_OutrasCob_UCOperationCompleted);
            }
            this.InvokeAsync("Insere_OutrasCob_UC", new object[] {
                        anidzona,
                        anidconta,
                        aniditem,
                        anmesfatura,
                        ananofatura,
                        addatalancto,
                        anvalor,
                        asideverest}, this.Insere_OutrasCob_UCOperationCompleted, userState);
        }
        
        private void OnInsere_OutrasCob_UCOperationCompleted(object arg) {
            if ((this.Insere_OutrasCob_UCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insere_OutrasCob_UCCompleted(this, new Insere_OutrasCob_UCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insere_Consumidor", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insere_Consumidor(
                    long anidconsumidor, 
                    long anidassociado, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor) {
            object[] results = this.Invoke("Insere_Consumidor", new object[] {
                        anidconsumidor,
                        anidassociado,
                        asnome,
                        asnomeempresa,
                        antipoinscricao,
                        asinscricao,
                        asinscricaoestadual,
                        ascep,
                        ascomplemento,
                        anidregiao,
                        asfone1,
                        asfone2,
                        asfone_celular,
                        addata_cadastro,
                        anidlocalentrega,
                        asci,
                        asci_orgao_emissor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insere_ConsumidorAsync(
                    long anidconsumidor, 
                    long anidassociado, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor) {
            this.Insere_ConsumidorAsync(anidconsumidor, anidassociado, asnome, asnomeempresa, antipoinscricao, asinscricao, asinscricaoestadual, ascep, ascomplemento, anidregiao, asfone1, asfone2, asfone_celular, addata_cadastro, anidlocalentrega, asci, asci_orgao_emissor, null);
        }
        
        /// <remarks/>
        public void Insere_ConsumidorAsync(
                    long anidconsumidor, 
                    long anidassociado, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor, 
                    object userState) {
            if ((this.Insere_ConsumidorOperationCompleted == null)) {
                this.Insere_ConsumidorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsere_ConsumidorOperationCompleted);
            }
            this.InvokeAsync("Insere_Consumidor", new object[] {
                        anidconsumidor,
                        anidassociado,
                        asnome,
                        asnomeempresa,
                        antipoinscricao,
                        asinscricao,
                        asinscricaoestadual,
                        ascep,
                        ascomplemento,
                        anidregiao,
                        asfone1,
                        asfone2,
                        asfone_celular,
                        addata_cadastro,
                        anidlocalentrega,
                        asci,
                        asci_orgao_emissor}, this.Insere_ConsumidorOperationCompleted, userState);
        }
        
        private void OnInsere_ConsumidorOperationCompleted(object arg) {
            if ((this.Insere_ConsumidorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insere_ConsumidorCompleted(this, new Insere_ConsumidorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Pagar_Fatura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Pagar_Fatura(string addata_pagto, long anidAgente, long annumero_fiscal, long aniduc, string adanomes, decimal anvalor_pagto, string ascobrar_multa) {
            object[] results = this.Invoke("Pagar_Fatura", new object[] {
                        addata_pagto,
                        anidAgente,
                        annumero_fiscal,
                        aniduc,
                        adanomes,
                        anvalor_pagto,
                        ascobrar_multa});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Pagar_FaturaAsync(string addata_pagto, long anidAgente, long annumero_fiscal, long aniduc, string adanomes, decimal anvalor_pagto, string ascobrar_multa) {
            this.Pagar_FaturaAsync(addata_pagto, anidAgente, annumero_fiscal, aniduc, adanomes, anvalor_pagto, ascobrar_multa, null);
        }
        
        /// <remarks/>
        public void Pagar_FaturaAsync(string addata_pagto, long anidAgente, long annumero_fiscal, long aniduc, string adanomes, decimal anvalor_pagto, string ascobrar_multa, object userState) {
            if ((this.Pagar_FaturaOperationCompleted == null)) {
                this.Pagar_FaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPagar_FaturaOperationCompleted);
            }
            this.InvokeAsync("Pagar_Fatura", new object[] {
                        addata_pagto,
                        anidAgente,
                        annumero_fiscal,
                        aniduc,
                        adanomes,
                        anvalor_pagto,
                        ascobrar_multa}, this.Pagar_FaturaOperationCompleted, userState);
        }
        
        private void OnPagar_FaturaOperationCompleted(object arg) {
            if ((this.Pagar_FaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pagar_FaturaCompleted(this, new Pagar_FaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Estornar_Pagamento_Fatura", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Estornar_Pagamento_Fatura(string addata_pagto, long anidAgente, long annumero_fiscal, long aniduc, string adanomes, decimal anvalor_pagto) {
            object[] results = this.Invoke("Estornar_Pagamento_Fatura", new object[] {
                        addata_pagto,
                        anidAgente,
                        annumero_fiscal,
                        aniduc,
                        adanomes,
                        anvalor_pagto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Estornar_Pagamento_FaturaAsync(string addata_pagto, long anidAgente, long annumero_fiscal, long aniduc, string adanomes, decimal anvalor_pagto) {
            this.Estornar_Pagamento_FaturaAsync(addata_pagto, anidAgente, annumero_fiscal, aniduc, adanomes, anvalor_pagto, null);
        }
        
        /// <remarks/>
        public void Estornar_Pagamento_FaturaAsync(string addata_pagto, long anidAgente, long annumero_fiscal, long aniduc, string adanomes, decimal anvalor_pagto, object userState) {
            if ((this.Estornar_Pagamento_FaturaOperationCompleted == null)) {
                this.Estornar_Pagamento_FaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstornar_Pagamento_FaturaOperationCompleted);
            }
            this.InvokeAsync("Estornar_Pagamento_Fatura", new object[] {
                        addata_pagto,
                        anidAgente,
                        annumero_fiscal,
                        aniduc,
                        adanomes,
                        anvalor_pagto}, this.Estornar_Pagamento_FaturaOperationCompleted, userState);
        }
        
        private void OnEstornar_Pagamento_FaturaOperationCompleted(object arg) {
            if ((this.Estornar_Pagamento_FaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Estornar_Pagamento_FaturaCompleted(this, new Estornar_Pagamento_FaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insere_OutrasCob_UC_Hist", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insere_OutrasCob_UC_Hist(long anidzona, long anidconta, long aniditem, long anmesfatura, long ananofatura, string addatalancto, decimal anvalor, string asideverest, string ashistorico) {
            object[] results = this.Invoke("Insere_OutrasCob_UC_Hist", new object[] {
                        anidzona,
                        anidconta,
                        aniditem,
                        anmesfatura,
                        ananofatura,
                        addatalancto,
                        anvalor,
                        asideverest,
                        ashistorico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insere_OutrasCob_UC_HistAsync(long anidzona, long anidconta, long aniditem, long anmesfatura, long ananofatura, string addatalancto, decimal anvalor, string asideverest, string ashistorico) {
            this.Insere_OutrasCob_UC_HistAsync(anidzona, anidconta, aniditem, anmesfatura, ananofatura, addatalancto, anvalor, asideverest, ashistorico, null);
        }
        
        /// <remarks/>
        public void Insere_OutrasCob_UC_HistAsync(long anidzona, long anidconta, long aniditem, long anmesfatura, long ananofatura, string addatalancto, decimal anvalor, string asideverest, string ashistorico, object userState) {
            if ((this.Insere_OutrasCob_UC_HistOperationCompleted == null)) {
                this.Insere_OutrasCob_UC_HistOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsere_OutrasCob_UC_HistOperationCompleted);
            }
            this.InvokeAsync("Insere_OutrasCob_UC_Hist", new object[] {
                        anidzona,
                        anidconta,
                        aniditem,
                        anmesfatura,
                        ananofatura,
                        addatalancto,
                        anvalor,
                        asideverest,
                        ashistorico}, this.Insere_OutrasCob_UC_HistOperationCompleted, userState);
        }
        
        private void OnInsere_OutrasCob_UC_HistOperationCompleted(object arg) {
            if ((this.Insere_OutrasCob_UC_HistCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insere_OutrasCob_UC_HistCompleted(this, new Insere_OutrasCob_UC_HistCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insere_Consumidor_Novo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Insere_Consumidor_Novo(
                    long anidconsumidor, 
                    long anidassociado, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor, 
                    string asemail, 
                    string asnomepai, 
                    string asnomemae, 
                    string asprofissao, 
                    string asestadocivil, 
                    string asnaturalidade, 
                    int ancnae, 
                    int andiavcto) {
            object[] results = this.Invoke("Insere_Consumidor_Novo", new object[] {
                        anidconsumidor,
                        anidassociado,
                        asnome,
                        asnomeempresa,
                        antipoinscricao,
                        asinscricao,
                        asinscricaoestadual,
                        ascep,
                        ascomplemento,
                        anidregiao,
                        asfone1,
                        asfone2,
                        asfone_celular,
                        addata_cadastro,
                        anidlocalentrega,
                        asci,
                        asci_orgao_emissor,
                        asemail,
                        asnomepai,
                        asnomemae,
                        asprofissao,
                        asestadocivil,
                        asnaturalidade,
                        ancnae,
                        andiavcto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Insere_Consumidor_NovoAsync(
                    long anidconsumidor, 
                    long anidassociado, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor, 
                    string asemail, 
                    string asnomepai, 
                    string asnomemae, 
                    string asprofissao, 
                    string asestadocivil, 
                    string asnaturalidade, 
                    int ancnae, 
                    int andiavcto) {
            this.Insere_Consumidor_NovoAsync(anidconsumidor, anidassociado, asnome, asnomeempresa, antipoinscricao, asinscricao, asinscricaoestadual, ascep, ascomplemento, anidregiao, asfone1, asfone2, asfone_celular, addata_cadastro, anidlocalentrega, asci, asci_orgao_emissor, asemail, asnomepai, asnomemae, asprofissao, asestadocivil, asnaturalidade, ancnae, andiavcto, null);
        }
        
        /// <remarks/>
        public void Insere_Consumidor_NovoAsync(
                    long anidconsumidor, 
                    long anidassociado, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor, 
                    string asemail, 
                    string asnomepai, 
                    string asnomemae, 
                    string asprofissao, 
                    string asestadocivil, 
                    string asnaturalidade, 
                    int ancnae, 
                    int andiavcto, 
                    object userState) {
            if ((this.Insere_Consumidor_NovoOperationCompleted == null)) {
                this.Insere_Consumidor_NovoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsere_Consumidor_NovoOperationCompleted);
            }
            this.InvokeAsync("Insere_Consumidor_Novo", new object[] {
                        anidconsumidor,
                        anidassociado,
                        asnome,
                        asnomeempresa,
                        antipoinscricao,
                        asinscricao,
                        asinscricaoestadual,
                        ascep,
                        ascomplemento,
                        anidregiao,
                        asfone1,
                        asfone2,
                        asfone_celular,
                        addata_cadastro,
                        anidlocalentrega,
                        asci,
                        asci_orgao_emissor,
                        asemail,
                        asnomepai,
                        asnomemae,
                        asprofissao,
                        asestadocivil,
                        asnaturalidade,
                        ancnae,
                        andiavcto}, this.Insere_Consumidor_NovoOperationCompleted, userState);
        }
        
        private void OnInsere_Consumidor_NovoOperationCompleted(object arg) {
            if ((this.Insere_Consumidor_NovoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insere_Consumidor_NovoCompleted(this, new Insere_Consumidor_NovoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Atualiza_Consumidor_Novo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Atualiza_Consumidor_Novo(
                    long anidconsumidor, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor, 
                    string asemail, 
                    string asnomepai, 
                    string asnomemae, 
                    string asprofissao, 
                    string asestadocivil, 
                    string asnaturalidade, 
                    int ancnae, 
                    int andiavcto) {
            object[] results = this.Invoke("Atualiza_Consumidor_Novo", new object[] {
                        anidconsumidor,
                        asnome,
                        asnomeempresa,
                        antipoinscricao,
                        asinscricao,
                        asinscricaoestadual,
                        ascep,
                        ascomplemento,
                        anidregiao,
                        asfone1,
                        asfone2,
                        asfone_celular,
                        addata_cadastro,
                        anidlocalentrega,
                        asci,
                        asci_orgao_emissor,
                        asemail,
                        asnomepai,
                        asnomemae,
                        asprofissao,
                        asestadocivil,
                        asnaturalidade,
                        ancnae,
                        andiavcto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Atualiza_Consumidor_NovoAsync(
                    long anidconsumidor, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor, 
                    string asemail, 
                    string asnomepai, 
                    string asnomemae, 
                    string asprofissao, 
                    string asestadocivil, 
                    string asnaturalidade, 
                    int ancnae, 
                    int andiavcto) {
            this.Atualiza_Consumidor_NovoAsync(anidconsumidor, asnome, asnomeempresa, antipoinscricao, asinscricao, asinscricaoestadual, ascep, ascomplemento, anidregiao, asfone1, asfone2, asfone_celular, addata_cadastro, anidlocalentrega, asci, asci_orgao_emissor, asemail, asnomepai, asnomemae, asprofissao, asestadocivil, asnaturalidade, ancnae, andiavcto, null);
        }
        
        /// <remarks/>
        public void Atualiza_Consumidor_NovoAsync(
                    long anidconsumidor, 
                    string asnome, 
                    string asnomeempresa, 
                    long antipoinscricao, 
                    string asinscricao, 
                    string asinscricaoestadual, 
                    string ascep, 
                    string ascomplemento, 
                    long anidregiao, 
                    string asfone1, 
                    string asfone2, 
                    string asfone_celular, 
                    string addata_cadastro, 
                    long anidlocalentrega, 
                    string asci, 
                    string asci_orgao_emissor, 
                    string asemail, 
                    string asnomepai, 
                    string asnomemae, 
                    string asprofissao, 
                    string asestadocivil, 
                    string asnaturalidade, 
                    int ancnae, 
                    int andiavcto, 
                    object userState) {
            if ((this.Atualiza_Consumidor_NovoOperationCompleted == null)) {
                this.Atualiza_Consumidor_NovoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAtualiza_Consumidor_NovoOperationCompleted);
            }
            this.InvokeAsync("Atualiza_Consumidor_Novo", new object[] {
                        anidconsumidor,
                        asnome,
                        asnomeempresa,
                        antipoinscricao,
                        asinscricao,
                        asinscricaoestadual,
                        ascep,
                        ascomplemento,
                        anidregiao,
                        asfone1,
                        asfone2,
                        asfone_celular,
                        addata_cadastro,
                        anidlocalentrega,
                        asci,
                        asci_orgao_emissor,
                        asemail,
                        asnomepai,
                        asnomemae,
                        asprofissao,
                        asestadocivil,
                        asnaturalidade,
                        ancnae,
                        andiavcto}, this.Atualiza_Consumidor_NovoOperationCompleted, userState);
        }
        
        private void OnAtualiza_Consumidor_NovoOperationCompleted(object arg) {
            if ((this.Atualiza_Consumidor_NovoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Atualiza_Consumidor_NovoCompleted(this, new Atualiza_Consumidor_NovoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Insere_OutrasCob_UCCompletedEventHandler(object sender, Insere_OutrasCob_UCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insere_OutrasCob_UCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insere_OutrasCob_UCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Insere_ConsumidorCompletedEventHandler(object sender, Insere_ConsumidorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insere_ConsumidorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insere_ConsumidorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Pagar_FaturaCompletedEventHandler(object sender, Pagar_FaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pagar_FaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pagar_FaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Estornar_Pagamento_FaturaCompletedEventHandler(object sender, Estornar_Pagamento_FaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Estornar_Pagamento_FaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Estornar_Pagamento_FaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Insere_OutrasCob_UC_HistCompletedEventHandler(object sender, Insere_OutrasCob_UC_HistCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insere_OutrasCob_UC_HistCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insere_OutrasCob_UC_HistCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Insere_Consumidor_NovoCompletedEventHandler(object sender, Insere_Consumidor_NovoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insere_Consumidor_NovoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insere_Consumidor_NovoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void Atualiza_Consumidor_NovoCompletedEventHandler(object sender, Atualiza_Consumidor_NovoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Atualiza_Consumidor_NovoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Atualiza_Consumidor_NovoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591