//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integradora.ECommerce.FBits.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncCategoria.asmx")]
        public string Integradora_ECommerce_FBits_SyncCategoria {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncCategoria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncContaCorrente.asmx")]
        public string Integradora_ECommerce_FBits_br_com_ecommercestore_decisaoatacadista_integracao_SyncContaCorrente {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_br_com_ecommercestore_decisaoatacadista_integracao_Sy" +
                    "ncContaCorrente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncEstoque.asmx")]
        public string Integradora_ECommerce_FBits_SyncEstoque {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncEstoque"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncPedidoStatus.asmx")]
        public string Integradora_ECommerce_FBits_SyncPedidoStatus {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncPedidoStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncPedidoVenda.asmx")]
        public string Integradora_ECommerce_FBits_SyncPedidoVenda {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncPedidoVenda"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncProduto.asmx")]
        public string Integradora_ECommerce_FBits_SyncProduto {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncProduto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncProdutoCategoria.asmx")]
        public string Integradora_ECommerce_FBits_SyncProdutoCategoria {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncProdutoCategoria"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncProdutoCombo.asmx")]
        public string Integradora_ECommerce_FBits_SyncProdutoCombo {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncProdutoCombo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncProdutoEstoque.asmx")]
        public string Integradora_ECommerce_FBits_SyncProdutoEstoque {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncProdutoEstoque"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncProdutoFornecedor.asmx")]
        public string Integradora_ECommerce_FBits_SyncProdutoFornecedor {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncProdutoFornecedor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncProdutoImagem.asmx")]
        public string Integradora_ECommerce_FBits_SyncProdutoImagem {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncProdutoImagem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncProdutoPreco.asmx")]
        public string Integradora_ECommerce_FBits_SyncProdutoPreco {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncProdutoPreco"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncUsuario.asmx")]
        public string Integradora_ECommerce_FBits_SyncUsuario {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncUsuario"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://integracao.decisaoentrega.com.br/modelo007/SyncUsuarioEndereco.asmx")]
        public string Integradora_ECommerce_FBits_SyncUsuarioEndereco {
            get {
                return ((string)(this["Integradora_ECommerce_FBits_SyncUsuarioEndereco"]));
            }
        }
    }
}
