//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Integradora.ECommerce.Ajuri.AjuriEntradas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsEntradasBinding", Namespace="urn:WsEntradas")]
    public partial class WsEntradas : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ATUALIZAR_ENTRADAOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsEntradas() {
            this.Url = global::Integradora.Biblioteca.Dictionaries.Settings.AjuriURL_Entradas();
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ATUALIZAR_ENTRADACompletedEventHandler ATUALIZAR_ENTRADACompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:WsEntradas#ATUALIZAR_ENTRADA", RequestNamespace="urn:WsEntradas", ResponseNamespace="urn:WsEntradas")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string ATUALIZAR_ENTRADA(string xml_string) {
            object[] results = this.Invoke("ATUALIZAR_ENTRADA", new object[] {
                        xml_string});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ATUALIZAR_ENTRADAAsync(string xml_string) {
            this.ATUALIZAR_ENTRADAAsync(xml_string, null);
        }
        
        /// <remarks/>
        public void ATUALIZAR_ENTRADAAsync(string xml_string, object userState) {
            if ((this.ATUALIZAR_ENTRADAOperationCompleted == null)) {
                this.ATUALIZAR_ENTRADAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnATUALIZAR_ENTRADAOperationCompleted);
            }
            this.InvokeAsync("ATUALIZAR_ENTRADA", new object[] {
                        xml_string}, this.ATUALIZAR_ENTRADAOperationCompleted, userState);
        }
        
        private void OnATUALIZAR_ENTRADAOperationCompleted(object arg) {
            if ((this.ATUALIZAR_ENTRADACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ATUALIZAR_ENTRADACompleted(this, new ATUALIZAR_ENTRADACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ATUALIZAR_ENTRADACompletedEventHandler(object sender, ATUALIZAR_ENTRADACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ATUALIZAR_ENTRADACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ATUALIZAR_ENTRADACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591