//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integradora.ECommerce.GsGroup.ZoOmBox {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZoOmBox.WSSoap")]
    public interface WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.Autenticacao ValidaLogin(string paramCodigo, string paramCPF, string paramSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Autenticacao> ValidaLoginAsync(string paramCodigo, string paramCPF, string paramSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemDadosUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.DadosUsuario ObtemDadosUsuario(string paramCodigo, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemDadosUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.DadosUsuario> ObtemDadosUsuarioAsync(string paramCodigo, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarSenha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.RecuperacaoSenha RecuperarSenha(string paramCodigo, string paramCPF, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarSenha", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.RecuperacaoSenha> RecuperarSenhaAsync(string paramCodigo, string paramCPF, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterarSenha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.AlteracaoSenha AlterarSenha(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterarSenha", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.AlteracaoSenha> AlterarSenhaAsync(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.DadosCliente RecuperarCliente(string paramCPF, string paramCodigoUsuario, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.DadosCliente> RecuperarClienteAsync(string paramCPF, string paramCodigoUsuario, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pontuar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.Pontuacao Pontuar(string paramCodigoUsuario, string paramCPF, string paramValorGasto, string paramFormaPagamento, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pontuar", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Pontuacao> PontuarAsync(string paramCodigoUsuario, string paramCPF, string paramValorGasto, string paramFormaPagamento, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarFormasPagamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.FormasPagamento[] RecuperarFormasPagamento(string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarFormasPagamento", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.FormasPagamento[]> RecuperarFormasPagamentoAsync(string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCupomParaImpressao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.Impressao RecuperaCupomParaImpressao(long codigoPlataforma, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCupomParaImpressao", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Impressao> RecuperaCupomParaImpressaoAsync(long codigoPlataforma, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCuponsImpressos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.Impressao[] RecuperaCuponsImpressos(long codigoPlataforma, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCuponsImpressos", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Impressao[]> RecuperaCuponsImpressosAsync(long codigoPlataforma, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarErroImpressora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBox.ErroImpressora GerarErroImpressora(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarErroImpressora", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.ErroImpressora> GerarErroImpressoraAsync(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setNotificaVenda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setNotificaVenda(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setNotificaVenda", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setNotificaVendaAsync(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReprocessarVendas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReprocessarVendas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReprocessarVendas", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReprocessarVendasAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Autenticacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private DadosUsuario dadosUsuarioField;
        
        private FormasPagamento[] formasPagamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DadosUsuario DadosUsuario {
            get {
                return this.dadosUsuarioField;
            }
            set {
                this.dadosUsuarioField = value;
                this.RaisePropertyChanged("DadosUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public FormasPagamento[] FormasPagamento {
            get {
                return this.formasPagamentoField;
            }
            set {
                this.formasPagamentoField = value;
                this.RaisePropertyChanged("FormasPagamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private string codigoLojaField;
        
        private string nomeLojaField;
        
        private string nomeUsuarioField;
        
        private decimal saldoLojaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoLoja {
            get {
                return this.codigoLojaField;
            }
            set {
                this.codigoLojaField = value;
                this.RaisePropertyChanged("CodigoLoja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NomeLoja {
            get {
                return this.nomeLojaField;
            }
            set {
                this.nomeLojaField = value;
                this.RaisePropertyChanged("NomeLoja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NomeUsuario {
            get {
                return this.nomeUsuarioField;
            }
            set {
                this.nomeUsuarioField = value;
                this.RaisePropertyChanged("NomeUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal SaldoLoja {
            get {
                return this.saldoLojaField;
            }
            set {
                this.saldoLojaField = value;
                this.RaisePropertyChanged("SaldoLoja");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErroImpressora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Impressao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string textoField;
        
        private int quantidadeField;
        
        private System.DateTime dataHoraField;
        
        private string clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
                this.RaisePropertyChanged("Texto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("Quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
                this.RaisePropertyChanged("DataHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pontuacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private decimal saldoLojaField;
        
        private decimal vipsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal SaldoLoja {
            get {
                return this.saldoLojaField;
            }
            set {
                this.saldoLojaField = value;
                this.RaisePropertyChanged("SaldoLoja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Vips {
            get {
                return this.vipsField;
            }
            set {
                this.vipsField = value;
                this.RaisePropertyChanged("Vips");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private string nomeField;
        
        private decimal saldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("Saldo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AlteracaoSenha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperacaoSenha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FormasPagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : Integradora.ECommerce.GsGroup.ZoOmBox.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<Integradora.ECommerce.GsGroup.ZoOmBox.WSSoap>, Integradora.ECommerce.GsGroup.ZoOmBox.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.Autenticacao ValidaLogin(string paramCodigo, string paramCPF, string paramSenha, string paramChave) {
            return base.Channel.ValidaLogin(paramCodigo, paramCPF, paramSenha, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Autenticacao> ValidaLoginAsync(string paramCodigo, string paramCPF, string paramSenha, string paramChave) {
            return base.Channel.ValidaLoginAsync(paramCodigo, paramCPF, paramSenha, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.DadosUsuario ObtemDadosUsuario(string paramCodigo, string paramChave) {
            return base.Channel.ObtemDadosUsuario(paramCodigo, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.DadosUsuario> ObtemDadosUsuarioAsync(string paramCodigo, string paramChave) {
            return base.Channel.ObtemDadosUsuarioAsync(paramCodigo, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.RecuperacaoSenha RecuperarSenha(string paramCodigo, string paramCPF, string paramChave) {
            return base.Channel.RecuperarSenha(paramCodigo, paramCPF, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.RecuperacaoSenha> RecuperarSenhaAsync(string paramCodigo, string paramCPF, string paramChave) {
            return base.Channel.RecuperarSenhaAsync(paramCodigo, paramCPF, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.AlteracaoSenha AlterarSenha(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave) {
            return base.Channel.AlterarSenha(paramCodigo, paramCPF, paramSenhaAtual, paramNovaSenha, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.AlteracaoSenha> AlterarSenhaAsync(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave) {
            return base.Channel.AlterarSenhaAsync(paramCodigo, paramCPF, paramSenhaAtual, paramNovaSenha, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.DadosCliente RecuperarCliente(string paramCPF, string paramCodigoUsuario, string paramChave) {
            return base.Channel.RecuperarCliente(paramCPF, paramCodigoUsuario, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.DadosCliente> RecuperarClienteAsync(string paramCPF, string paramCodigoUsuario, string paramChave) {
            return base.Channel.RecuperarClienteAsync(paramCPF, paramCodigoUsuario, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.Pontuacao Pontuar(string paramCodigoUsuario, string paramCPF, string paramValorGasto, string paramFormaPagamento, string paramChave) {
            return base.Channel.Pontuar(paramCodigoUsuario, paramCPF, paramValorGasto, paramFormaPagamento, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Pontuacao> PontuarAsync(string paramCodigoUsuario, string paramCPF, string paramValorGasto, string paramFormaPagamento, string paramChave) {
            return base.Channel.PontuarAsync(paramCodigoUsuario, paramCPF, paramValorGasto, paramFormaPagamento, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.FormasPagamento[] RecuperarFormasPagamento(string paramChave) {
            return base.Channel.RecuperarFormasPagamento(paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.FormasPagamento[]> RecuperarFormasPagamentoAsync(string paramChave) {
            return base.Channel.RecuperarFormasPagamentoAsync(paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.Impressao RecuperaCupomParaImpressao(long codigoPlataforma, string paramChave) {
            return base.Channel.RecuperaCupomParaImpressao(codigoPlataforma, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Impressao> RecuperaCupomParaImpressaoAsync(long codigoPlataforma, string paramChave) {
            return base.Channel.RecuperaCupomParaImpressaoAsync(codigoPlataforma, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.Impressao[] RecuperaCuponsImpressos(long codigoPlataforma, string paramChave) {
            return base.Channel.RecuperaCuponsImpressos(codigoPlataforma, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.Impressao[]> RecuperaCuponsImpressosAsync(long codigoPlataforma, string paramChave) {
            return base.Channel.RecuperaCuponsImpressosAsync(codigoPlataforma, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBox.ErroImpressora GerarErroImpressora(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave) {
            return base.Channel.GerarErroImpressora(paramImpressora, paramMensagemErro, paramCodigoErro, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBox.ErroImpressora> GerarErroImpressoraAsync(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave) {
            return base.Channel.GerarErroImpressoraAsync(paramImpressora, paramMensagemErro, paramCodigoErro, paramChave);
        }
        
        public string setNotificaVenda(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash) {
            return base.Channel.setNotificaVenda(documento, numeroCupom, dataHora, loja, pdv, categoriaProduto, valor, hash);
        }
        
        public System.Threading.Tasks.Task<string> setNotificaVendaAsync(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash) {
            return base.Channel.setNotificaVendaAsync(documento, numeroCupom, dataHora, loja, pdv, categoriaProduto, valor, hash);
        }
        
        public string ReprocessarVendas() {
            return base.Channel.ReprocessarVendas();
        }
        
        public System.Threading.Tasks.Task<string> ReprocessarVendasAsync() {
            return base.Channel.ReprocessarVendasAsync();
        }
    }
}
