//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integradora.ECommerce.GsGroup.ZoOmBoxFilial {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZoOmBoxFilial.WSSoap")]
    public interface WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Autenticacao ValidaLogin(string paramCodigo, string paramCPF, string paramSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidaLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Autenticacao> ValidaLoginAsync(string paramCodigo, string paramCPF, string paramSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemDadosUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosUsuario ObtemDadosUsuario(string paramCodigo, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtemDadosUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosUsuario> ObtemDadosUsuarioAsync(string paramCodigo, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarSenha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperacaoSenha RecuperarSenha(string paramCodigo, string paramCPF, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarSenha", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperacaoSenha> RecuperarSenhaAsync(string paramCodigo, string paramCPF, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterarSenha", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.AlteracaoSenha AlterarSenha(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlterarSenha", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.AlteracaoSenha> AlterarSenhaAsync(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarCliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosCliente RecuperarCliente(string paramCPF, string paramCodigoUsuario, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosCliente> RecuperarClienteAsync(string paramCPF, string paramCodigoUsuario, string paramChave);
        
        // CODEGEN: Parameter 'idImpressora' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pontuar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarResponse Pontuar(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pontuar", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarResponse> PontuarAsync(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarFormasPagamento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.FormasPagamento[] RecuperarFormasPagamento(string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperarFormasPagamento", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.FormasPagamento[]> RecuperarFormasPagamentoAsync(string paramChave);
        
        // CODEGEN: Parameter 'paramIdImpressora' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCupomParaImpressao", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoResponse RecuperaCupomParaImpressao(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCupomParaImpressao", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoResponse> RecuperaCupomParaImpressaoAsync(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCuponsImpressos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Impressao[] RecuperaCuponsImpressos(long codigoPlataforma, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecuperaCuponsImpressos", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Impressao[]> RecuperaCuponsImpressosAsync(long codigoPlataforma, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarErroImpressora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.ErroImpressora GerarErroImpressora(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GerarErroImpressora", ReplyAction="*")]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.ErroImpressora> GerarErroImpressoraAsync(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setNotificaVenda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string setNotificaVenda(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/setNotificaVenda", ReplyAction="*")]
        System.Threading.Tasks.Task<string> setNotificaVendaAsync(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReprocessarVendas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReprocessarVendas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReprocessarVendas", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ReprocessarVendasAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Autenticacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private DadosUsuario dadosUsuarioField;
        
        private FormasPagamento[] formasPagamentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public DadosUsuario DadosUsuario {
            get {
                return this.dadosUsuarioField;
            }
            set {
                this.dadosUsuarioField = value;
                this.RaisePropertyChanged("DadosUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        public FormasPagamento[] FormasPagamento {
            get {
                return this.formasPagamentoField;
            }
            set {
                this.formasPagamentoField = value;
                this.RaisePropertyChanged("FormasPagamento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosUsuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private string codigoLojaField;
        
        private string nomeLojaField;
        
        private string nomeUsuarioField;
        
        private decimal saldoLojaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoLoja {
            get {
                return this.codigoLojaField;
            }
            set {
                this.codigoLojaField = value;
                this.RaisePropertyChanged("CodigoLoja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NomeLoja {
            get {
                return this.nomeLojaField;
            }
            set {
                this.nomeLojaField = value;
                this.RaisePropertyChanged("NomeLoja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NomeUsuario {
            get {
                return this.nomeUsuarioField;
            }
            set {
                this.nomeUsuarioField = value;
                this.RaisePropertyChanged("NomeUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal SaldoLoja {
            get {
                return this.saldoLojaField;
            }
            set {
                this.saldoLojaField = value;
                this.RaisePropertyChanged("SaldoLoja");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErroImpressora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Impressao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string textoField;
        
        private int quantidadeField;
        
        private System.DateTime dataHoraField;
        
        private string clienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
                this.RaisePropertyChanged("Texto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
                this.RaisePropertyChanged("Quantidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime DataHora {
            get {
                return this.dataHoraField;
            }
            set {
                this.dataHoraField = value;
                this.RaisePropertyChanged("DataHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Cliente {
            get {
                return this.clienteField;
            }
            set {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Pontuacao : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private decimal saldoLojaField;
        
        private decimal vipsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal SaldoLoja {
            get {
                return this.saldoLojaField;
            }
            set {
                this.saldoLojaField = value;
                this.RaisePropertyChanged("SaldoLoja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Vips {
            get {
                return this.vipsField;
            }
            set {
                this.vipsField = value;
                this.RaisePropertyChanged("Vips");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DadosCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private string nomeField;
        
        private decimal saldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
                this.RaisePropertyChanged("Saldo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AlteracaoSenha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecuperacaoSenha : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool sucessoField;
        
        private string mensagemField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Sucesso {
            get {
                return this.sucessoField;
            }
            set {
                this.sucessoField = value;
                this.RaisePropertyChanged("Sucesso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
                this.RaisePropertyChanged("Mensagem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class FormasPagamento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("Codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("Nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pontuar", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PontuarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string paramCodigoUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string paramCPF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string paramValorGasto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string paramFormaPagamento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string paramChave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> idImpressora;
        
        public PontuarRequest() {
        }
        
        public PontuarRequest(string paramCodigoUsuario, string paramCPF, string paramValorGasto, string paramFormaPagamento, string paramChave, System.Nullable<long> idImpressora) {
            this.paramCodigoUsuario = paramCodigoUsuario;
            this.paramCPF = paramCPF;
            this.paramValorGasto = paramValorGasto;
            this.paramFormaPagamento = paramFormaPagamento;
            this.paramChave = paramChave;
            this.idImpressora = idImpressora;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PontuarResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PontuarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Pontuacao PontuarResult;
        
        public PontuarResponse() {
        }
        
        public PontuarResponse(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Pontuacao PontuarResult) {
            this.PontuarResult = PontuarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperaCupomParaImpressao", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperaCupomParaImpressaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long codigoPlataforma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string paramChave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> paramIdImpressora;
        
        public RecuperaCupomParaImpressaoRequest() {
        }
        
        public RecuperaCupomParaImpressaoRequest(long codigoPlataforma, string paramChave, System.Nullable<long> paramIdImpressora) {
            this.codigoPlataforma = codigoPlataforma;
            this.paramChave = paramChave;
            this.paramIdImpressora = paramIdImpressora;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecuperaCupomParaImpressaoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class RecuperaCupomParaImpressaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Impressao RecuperaCupomParaImpressaoResult;
        
        public RecuperaCupomParaImpressaoResponse() {
        }
        
        public RecuperaCupomParaImpressaoResponse(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Impressao RecuperaCupomParaImpressaoResult) {
            this.RecuperaCupomParaImpressaoResult = RecuperaCupomParaImpressaoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap>, Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Autenticacao ValidaLogin(string paramCodigo, string paramCPF, string paramSenha, string paramChave) {
            return base.Channel.ValidaLogin(paramCodigo, paramCPF, paramSenha, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Autenticacao> ValidaLoginAsync(string paramCodigo, string paramCPF, string paramSenha, string paramChave) {
            return base.Channel.ValidaLoginAsync(paramCodigo, paramCPF, paramSenha, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosUsuario ObtemDadosUsuario(string paramCodigo, string paramChave) {
            return base.Channel.ObtemDadosUsuario(paramCodigo, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosUsuario> ObtemDadosUsuarioAsync(string paramCodigo, string paramChave) {
            return base.Channel.ObtemDadosUsuarioAsync(paramCodigo, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperacaoSenha RecuperarSenha(string paramCodigo, string paramCPF, string paramChave) {
            return base.Channel.RecuperarSenha(paramCodigo, paramCPF, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperacaoSenha> RecuperarSenhaAsync(string paramCodigo, string paramCPF, string paramChave) {
            return base.Channel.RecuperarSenhaAsync(paramCodigo, paramCPF, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.AlteracaoSenha AlterarSenha(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave) {
            return base.Channel.AlterarSenha(paramCodigo, paramCPF, paramSenhaAtual, paramNovaSenha, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.AlteracaoSenha> AlterarSenhaAsync(string paramCodigo, string paramCPF, string paramSenhaAtual, string paramNovaSenha, string paramChave) {
            return base.Channel.AlterarSenhaAsync(paramCodigo, paramCPF, paramSenhaAtual, paramNovaSenha, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosCliente RecuperarCliente(string paramCPF, string paramCodigoUsuario, string paramChave) {
            return base.Channel.RecuperarCliente(paramCPF, paramCodigoUsuario, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.DadosCliente> RecuperarClienteAsync(string paramCPF, string paramCodigoUsuario, string paramChave) {
            return base.Channel.RecuperarClienteAsync(paramCPF, paramCodigoUsuario, paramChave);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarResponse Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap.Pontuar(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest request) {
            return base.Channel.Pontuar(request);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Pontuacao Pontuar(string paramCodigoUsuario, string paramCPF, string paramValorGasto, string paramFormaPagamento, string paramChave, System.Nullable<long> idImpressora) {
            Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest inValue = new Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest();
            inValue.paramCodigoUsuario = paramCodigoUsuario;
            inValue.paramCPF = paramCPF;
            inValue.paramValorGasto = paramValorGasto;
            inValue.paramFormaPagamento = paramFormaPagamento;
            inValue.paramChave = paramChave;
            inValue.idImpressora = idImpressora;
            Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarResponse retVal = ((Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap)(this)).Pontuar(inValue);
            return retVal.PontuarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarResponse> Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap.PontuarAsync(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest request) {
            return base.Channel.PontuarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarResponse> PontuarAsync(string paramCodigoUsuario, string paramCPF, string paramValorGasto, string paramFormaPagamento, string paramChave, System.Nullable<long> idImpressora) {
            Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest inValue = new Integradora.ECommerce.GsGroup.ZoOmBoxFilial.PontuarRequest();
            inValue.paramCodigoUsuario = paramCodigoUsuario;
            inValue.paramCPF = paramCPF;
            inValue.paramValorGasto = paramValorGasto;
            inValue.paramFormaPagamento = paramFormaPagamento;
            inValue.paramChave = paramChave;
            inValue.idImpressora = idImpressora;
            return ((Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap)(this)).PontuarAsync(inValue);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.FormasPagamento[] RecuperarFormasPagamento(string paramChave) {
            return base.Channel.RecuperarFormasPagamento(paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.FormasPagamento[]> RecuperarFormasPagamentoAsync(string paramChave) {
            return base.Channel.RecuperarFormasPagamentoAsync(paramChave);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoResponse Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap.RecuperaCupomParaImpressao(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest request) {
            return base.Channel.RecuperaCupomParaImpressao(request);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Impressao RecuperaCupomParaImpressao(long codigoPlataforma, string paramChave, System.Nullable<long> paramIdImpressora) {
            Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest inValue = new Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest();
            inValue.codigoPlataforma = codigoPlataforma;
            inValue.paramChave = paramChave;
            inValue.paramIdImpressora = paramIdImpressora;
            Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoResponse retVal = ((Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap)(this)).RecuperaCupomParaImpressao(inValue);
            return retVal.RecuperaCupomParaImpressaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoResponse> Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap.RecuperaCupomParaImpressaoAsync(Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest request) {
            return base.Channel.RecuperaCupomParaImpressaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoResponse> RecuperaCupomParaImpressaoAsync(long codigoPlataforma, string paramChave, System.Nullable<long> paramIdImpressora) {
            Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest inValue = new Integradora.ECommerce.GsGroup.ZoOmBoxFilial.RecuperaCupomParaImpressaoRequest();
            inValue.codigoPlataforma = codigoPlataforma;
            inValue.paramChave = paramChave;
            inValue.paramIdImpressora = paramIdImpressora;
            return ((Integradora.ECommerce.GsGroup.ZoOmBoxFilial.WSSoap)(this)).RecuperaCupomParaImpressaoAsync(inValue);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Impressao[] RecuperaCuponsImpressos(long codigoPlataforma, string paramChave) {
            return base.Channel.RecuperaCuponsImpressos(codigoPlataforma, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.Impressao[]> RecuperaCuponsImpressosAsync(long codigoPlataforma, string paramChave) {
            return base.Channel.RecuperaCuponsImpressosAsync(codigoPlataforma, paramChave);
        }
        
        public Integradora.ECommerce.GsGroup.ZoOmBoxFilial.ErroImpressora GerarErroImpressora(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave) {
            return base.Channel.GerarErroImpressora(paramImpressora, paramMensagemErro, paramCodigoErro, paramChave);
        }
        
        public System.Threading.Tasks.Task<Integradora.ECommerce.GsGroup.ZoOmBoxFilial.ErroImpressora> GerarErroImpressoraAsync(long paramImpressora, string paramMensagemErro, string paramCodigoErro, string paramChave) {
            return base.Channel.GerarErroImpressoraAsync(paramImpressora, paramMensagemErro, paramCodigoErro, paramChave);
        }
        
        public string setNotificaVenda(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash) {
            return base.Channel.setNotificaVenda(documento, numeroCupom, dataHora, loja, pdv, categoriaProduto, valor, hash);
        }
        
        public System.Threading.Tasks.Task<string> setNotificaVendaAsync(string documento, decimal numeroCupom, System.DateTime dataHora, int loja, string pdv, int categoriaProduto, decimal valor, string hash) {
            return base.Channel.setNotificaVendaAsync(documento, numeroCupom, dataHora, loja, pdv, categoriaProduto, valor, hash);
        }
        
        public string ReprocessarVendas() {
            return base.Channel.ReprocessarVendas();
        }
        
        public System.Threading.Tasks.Task<string> ReprocessarVendasAsync() {
            return base.Channel.ReprocessarVendasAsync();
        }
    }
}
